plugins { id 'com.android.application' }
android {
    namespace 'com.example.todolist'
    compileSdk 37
    defaultConfig {
        applicationId 'com.example.todolist'
        minSdk 26
        targetSdk 37
        versionCode 12
        versionName '2.4'
        testInstrumentationRunner 'com.example.todolist.IntegrationTestRunner'
        javaCompileOptions { annotationProcessorOptions { arguments += ['room.schemaLocation': "$projectDir/schemas".toString()] } }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies {
    implementation 'androidx.room:room-runtime:2.8.4'
    annotationProcessor 'androidx.room:room-compiler:2.8.4'
    testImplementation 'junit:junit:4.13.2'
}
